version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - cd frontend
      - npm install && npm ci
    finally:
      - pwd
  build:
    commands:
      - echo Building static site..
      - npm run build
      - echo Run tests...
      - CI=true npm test

artifacts:
  type: zip
  paths:
    - 'frontend/build/**/*'
    - 'frontend-infrastructure/**/*'

cache:
  paths:
    - 'frontend/node_modules/**/*'
