name: "Automerge Dependabot"

on:
  pull_request:

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'pankajagrawal16'
    steps:
      - uses: actions/github-script@v3
        
        with:
          script: |
            github.pullRequests.submitReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })
          github-token: ${{ secrets.AUTOMERGE }}
