name: Build Frontend Infra

on:
  pull_request:
    branches:
      - master
    paths:
      - 'frontend-infrastructure/**'
  push:
    branches:
      - master
    paths:
      - 'frontend-infrastructure/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [8, 11.0.x]
        node-version: [14.x]
    name: Java ${{ matrix.java }} and Node ${{ matrix.node-version }}
    env:
      OS: ${{ matrix.os }}
      JAVA: ${{ matrix.java-version }}
      AWS_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: build frontend
        env:
          CI: false
        run: |
          cd frontend
          yarn
          yarn build
          yarn test
          cd ..
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        working-directory: ./
        run: |
          cd ./frontend-infrastructure
          mvn -B package --file pom.xml

  savepr:
    runs-on: ubuntu-latest
    name: Save PR number if running on PR by dependabot
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Create Directory and save issue
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }}
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        name: Updload artifact
        with:
          name: pr
          path: pr/
